name: PLC Test Automation

on:
  push:
    paths:
      - '**/*.gx3'  # Trigger when a .gx3 file changes

jobs:
  test-plc:
    runs-on: windows-latest  # Using a Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1  # Set up MSBuild for .NET Framework

      - name: Install Dependencies
        run: |
          choco install microsoft-build-tools  # Install MSBuild tools
          
      - name: Build C# Test Script (using MSBuild)
        run: |
          # Correct path to the .csproj file relative to the repository root
          msbuild ./PLCscript-test/PLCscript-test.csproj /p:Configuration=Release

      - name: Run PLC Test
        run: |
          Start-Process -FilePath "PLCscript-test\bin\Release\PLCscript-test.exe" -NoNewWindow -Wait